export const GET_ALBUMS = 'GET_ALBUMS';
export const ALBUMS_ERROR = 'ALBUMS_ERROR';

export const SET_CURRENT_ALBUM = 'SET_CURRENT_ALBUM';
export const CLEAR_CURRENT_ALBUM = 'CLEAR_CURRENT_ALBUM';

export const SET_LOADING_ALBUMS = 'SET_LOADING_ALBUMS';
export const SET_LOADING_IMAGES = 'SET_LOADING_IMAGES';

export const GET_IMAGES = 'GET_IMAGES';
export const SET_FILTERED_IMAGES = 'SET_FILTERED_IMAGES';
export const IMAGES_ERROR = 'IMAGES_ERROR';

export const SET_CURRENT_IMAGE = 'SET_CURRENT_IMAGE';
export const CLEAR_CURRENT_IMAGE = 'CLEAR_CURRENT_IMAGE';